spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crypto_bot
    username: root
    password: root
    hikari:
      schema: currency_crypto
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS currency_crypto

  liquibase:
    change-log: classpath:db\changelog_init.xml
    default-schema: currency_crypto
    drop-first: false
    enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: none
        default_schema: currency_crypto

telegram:
  bot:
    token: 5907758451:AAE8Wh6DWZF-Ya_Zm6Mq9VOTU_ztaqHwobI
    username: Cur_test_work_bot

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

frequency-course-updates: 120000
frequency-send-notification: 600000

logging:
  level:
    root: info